os:
  - linux
  - osx

sudo:
  - false

cache:
  directories:
    - node_modules

env:
  - NODE_VER=0.10
  - NODE_VER=0.12
  - NODE_VER=4
  - NODE_VER=5

matrix:
  fast_finish: true

notifications:
    slack: vile-team:7m87AOerZQ1inYwPxxh5kBJs

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source $(brew --prefix nvm)/nvm.sh; fi
  - uname -a
  - nvm --version
  - nvm install $NODE_VER
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm use --delete-prefix v$NODE_VER; fi
  - npm install -g npm
  - node --version
  - npm --version

install:
  - npm install

git:
  depth: 1

branches:
  only:
    - master

script:
  - npm run test-ci-build
