os:
  - osx

sudo:
  - false

cache:
  directories:
    - node_modules

env:
  - NODE_VER="4.4.2"

notifications:
    slack: vile-team:7m87AOerZQ1inYwPxxh5kBJs

install:
  - uname -a
  - brew update
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm --version
  - nvm install $NODE_VER
  - nvm use --delete-prefix v$NODE_VER
  - node --version
  - npm --version
  - npm install

git:
  depth: 1

script:
  - npm run test-ci-build
