os: osx
sudo: false
language: node_js
node_js: "4.4.0"

install:
  - rm -rf ~/.nvm
  - git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 4.4.0
  - node --version
  - npm install

git:
  depth: 1

script:
  - npm run test-ci-build
