os: osx
sudo: false

env:
  - NODE_VER="4.4.2"

install:
  - brew update
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm --version
  - nvm install $NODE_VER
  - node --version
  - npm --version
  - npm install

git:
  depth: 1

script:
  - npm run test-ci-build
