os:
  - osx
  - linux

language: node_js

node_js:
  - "4"
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NPM_VER=2.x.x
  - NPM_VER=3.x.x
  - NPM_VER=4.x.x

matrix:
  fast_finish: true

before_install:
  - uname -a
  - nvm --version
  - npm install -g npm@$NPM_VER
  - node --version
  - npm --version

git:
  depth: 10

branches:
  only:
    - master

before_script:
  - echo "no-op"

script:
  - npm run -s compile
  - npm run -s test
