os:
  - osx
  - linux

language: node_js

node_js:
  - "4"
  - "6"
  - "7"
  - "8"

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.9

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

matrix:
  fast_finish: true

before_install:
  - uname -a
  - nvm --version
  - node --version
  - npm --version

git:
  depth: 10

branches:
  only:
    - master

install:
  - npm i

before_script:
  - echo "no-op"

script:
  - npm run -s compile
  - npm run -s test
