os:
  - osx
  - linux

sudo: false

cache:
  directories:
    - ~/.cache/yarn
    - node_modules

env:
  - NODE_VER=4 NPM_VER=2.x.x
  - NODE_VER=4 NPM_VER=3.x.x
  - NODE_VER=4 NPM_VER=4.x.x
  - NODE_VER=6 NPM_VER=2.x.x
  - NODE_VER=6 NPM_VER=3.x.x
  - NODE_VER=6 NPM_VER=4.x.x

matrix:
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source $(brew --prefix nvm)/nvm.sh; fi
  - uname -a
  - nvm --version
  - nvm install $NODE_VER
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm use --delete-prefix v$NODE_VER; fi
  - npm install -g npm@$NPM_VER
  - npm i -g yarn
  - node --version
  - npm --version

install:
  - yarn

git:
  depth: 10

branches:
  only:
    - master

before_script:
  - echo "no-op"

script:
  - npm run -s test-ci-build
