vile:
  ignore: [
      "node_modules",
      ".build",
      ".test",
      ".git",
      "tags",
      "lib",
      "coverage",
      "typings",
      "tmp",
      "tags",
      ".eslintrc",
      ".eslintignore",
      ".node-version",
      ".tsdrc",
      "vendor"
    ]

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [ "pryjs", "@brentlintner/*" ]

length:
  config:
    file: 120
    line: 80

coverage:
  config:
    path: coverage/lcov.info

tslint:
  config: tslint.json

rubycritic:
  config:
    paths: [ "ruby" ]
    rating: "A"

license:
  config:
    ignored: [ "tslint" ]
    disallowed: [ ]
    allowed: [
      "MIT",
      "MPL",
      "MPL-2.0",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "Unlicense",
      "Artistic-2.0",
      "ISC",
      "WTFPL",
      "Apache",
      "Apache-2.0",
      "Apache 2.0",
      "Apache*",
      "Apachev2",
      "WTFPL",
      "GPL"
    ]
