vile:
  allow: []
  ignore: [
      "node_modules",
      ".build",
      ".test",
      ".git",
      "tags",
      "tsconfig.json",
      "/lib",
      "coverage",
      "typings",
      "tmp",
      "tags",
      ".eslintrc",
      ".eslintignore",
      ".node-version",
      ".tsdrc",
      "vendor"
    ]

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [
        "mocha",
        "babel-cli",
        "coffee-script",
        "istanbul",
        "release-it",
        "typescript",
        "wrench",
        "pryjs",
        "@forthright/*"
      ]

length:
  config:
    file: 120
    line: 80
  ignore: [ "test" ]

coverage:
  config:
    path: coverage/lcov.info

tslint:
  config: tslint.json

license:
  config:
    ignored: [ "tslint" ]
    disallowed: [ ]
    allowed: [
      "MIT",
      "MPL",
      "MPL-2.0",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "Unlicense",
      "Artistic-2.0",
      "ISC",
      "WTFPL",
      "Apache",
      "Apache-2.0",
      "Apache 2.0",
      "Apache*",
      "Apachev2",
      "WTFPL",
      "GPL"
    ]
