vile:
  ignore: [
      "node_modules",
      ".build",
      ".test",
      ".git",
      "tags",
      "lib",
      "coverage",
      "typings",
      "tmp",
      "tags",
      ".eslintrc",
      ".eslintignore",
      ".node-version",
      ".tsdrc",
      "vendor"
    ]

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [ "pryjs", "@brentlintner/*" ]

rubycritic:
  config:
    method_count: 10
    complexity: 80
    churn: 20
    rating: "A"
  ignore: .rcignore

license:
  config: [
      "MPL-2.0",
      "MIT",
      "MIT*",
      "The MIT License",
      "MIT License",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD*",
      "BSD-like",
      "APACHEv2",
      "Unlicense",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "BSD-3-Clause AND MIT",
      "Artistic-2.0",
      "(BSD-2-Clause OR MIT OR Apache-2.0)",
      "ISC",
      "WTFPL",
      "(BSD-2-Clause OR WTFPL)",
      "Apache2",
      "Apache",
      "Apache*",
      "Apache License 2.0",
      "Apache 2.0",
      "Apache-2.0",
      "WTFPL"
    ]
