vile:
  ignore:
    - ".*"
    - coverage
    - doc
    - "*.json"
    - LICENSE
    - "*.lock"
    - "*.log"
    - "*.md"
    - node_modules
    - src/@types
    - tags
    - test/fixtures
    - test/mocha.opts
    - tmp
    - "*.yml"

depcheck:
  config:
    ignore_dev_deps: true
    ignore_deps:
      - "@types/**"
      - "vile-**"
    ignore_dirs:
      - src
      - .docs
      - node_modules
      - coverage
      - tmp

retire:
  config:
    node: true
    package: true
    js: false
    ignore:
      - .docs

synt:
  ignore: lib

comment:
  ignore: lib

eclint:
  ignore: lib

language:
  ignore: lib

stat:
  allow:
    - src
    - test
  ignore:
    - src/@types/**

coverage:
  config:
    path: coverage/lcov.info

license:
  config:
    allowed:
      - MIT
      - ISC
      - MPL-2.0
      - LGPL
      - BSD
      - Apache
      - Unlicense
      - Artistic
      - WTFPL
      - Public Domain
      - CC-BY-3.0
    ignored:
      - classifier   # MIT https://github.com/harthur/classifier/blob/master/LICENSE
      - event-stream # MIT https://github.com/dominictarr/event-stream/blob/master/LICENCE
      - goo.gl       # See: https://github.com/kaimallea/node-googl/issues/14
      - jsonify      # Public Domain https://github.com/substack/jsonify/blob/master/package.json#L29
      - map-stream   # MIT https://github.com/dominictarr/map-stream/blob/master/LICENCE
      - retire       # Apache-2.0 https://github.com/RetireJS/retire.js/blob/master/LICENSE.md
      - semver-utils # Apache-2.0 https://git.daplie.com/coolaj86/semver-utils/blob/master/package.json#L20
