vile:
  plugins: [
      "coffeelint",
      "comment",
      "constable",
      "depcheck",
      "eslint",
      "html-validator",
      "htmllint",
      "jshint",
      "length",
      "license",
      "ncu",
      "newline",
      "nsp",
      "readme",
      "reek",
      "rubocop",
      "rubycritic",
      "semver",
      "tslint",
      "whitespace"
    ]

  ignore: [
      "node_modules",
      "bower_components",
      ".build",
      ".test",
      ".log",
      "coverage",
      "typings",
      "lib"
    ]

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [ "pryjs" ]

eslint:
  config: .eslintrc
  ignore: .eslintignore

tslint:
  config: tslint.json
  ignore : .tslintignore

csslint:
  config: .csslintrc
  ignore: .csslintignore

jshint:
  config: .jshintrc
  ignore: .jshintignore

coffeelint:
  config: coffeelint.json

length:
  config:
    file: 250
    line: 80

license:
  config: [
      "MPL-2.0",
      "MIT",
      "MIT*",
      "The MIT License",
      "MIT License",
      "Public Domain",
      "PSF",
      "BSD",
      "BSD*",
      "BSD-like",
      "APACHEv2",
      "Unlicense",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "BSD-3-Clause AND MIT",
      "Artistic-2.0",
      "(BSD-2-Clause OR MIT OR Apache-2.0)",
      "ISC",
      "WTFPL",
      "(BSD-2-Clause OR WTFPL)",
      "Apache2",
      "Apache",
      "Apache*",
      "Apache License 2.0",
      "Apache 2.0",
      "Apache-2.0",
      "WTFPL"
    ]
  ignore: [
      "ansi",
      "assert-plus",
      "bindings",
      "buffers",
      "cli-color",
      "commander",
      "config-chain",
      "css-parse",
      "css-stringify",
      "css",
      "cycle",
      "debug",
      "dreamopt",
      "growl",
      "microee",
      "ms",
      "pkginfo",
      "uglify-js"
    ]

