version: "#{build}"

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

skip_tags: true

clone_depth: 5

build: off

environment:
    nodejs_version: "4.4.2"

install:
  - ps: Install-Product nodejs $env:nodejs_version x64
  - npm install

test_script:
  - npm run test-ci-build

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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

  - provider: Email
    to:
      - brent.lintner@gmail.com
    on_build_status_changed: true
