version: "#{build}"

os: Visual Studio 2015

cache:
  - node_modules

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

skip_tags: true

clone_depth: 1

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - ver && node --version && npm --version
  - npm install

test_script:
  - npm run test-ci-build

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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

  - provider: Email
    to:
      - brent.lintner@gmail.com
    on_build_status_changed: true
