version: "#{build}"

os: Visual Studio 2015

cache:
  - node_modules -> package.json

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8.0.0

matrix:
  fast_finish: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

skip_tags: true

clone_depth: 10

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install -g npm@$env:npm_version
  - ver && node --version && npm --version
  - npm i

test_script:
  - npm run -s compile
  - npm run -s test
